/*
 * Parser/serializer for RuneScape: Dragonwilds' dedicated-server config
 * file, DedicatedServer.ini.
 *
 * Format background: Dragonwilds' dedicated server (a free "RuneScape:
 * Dragonwilds - Dedicated Servers" product on Steam, built on Unreal
 * Engine) is configured through a single small INI file with one section:
 *
 *   [/Script/Dominion.DedicatedServerSettings]
 *   OwnerId=<your player ID>
 *   ServerName=<server browser name>
 *   DefaultWorldName=<world created on first launch>
 *   AdminPassword=<Server Management access password>
 *   WorldPassword=<optional join password>
 *   ServerGuid=<auto-generated unique id; do not hand-edit>
 *
 * On Linux the file lives at
 *   .../RSDragonwilds/Saved/Config/Linux/DedicatedServer.ini
 * On Windows at
 *   .../RSDragonwilds/Saved/Config/WindowsServer/DedicatedServer.ini
 *
 * OwnerId, ServerName, DefaultWorldName, and AdminPassword are mandatory —
 * per Jagex's own documentation, the server will not start without an
 * OwnerId set. WorldPassword is optional (blank = anyone can join).
 * ServerGuid is generated by the server itself on first run and should be
 * left alone; this tool preserves it untouched if present in an uploaded
 * file, and omits it (letting the server generate a fresh one) if absent.
 * The listen port is NOT part of this file — it's set via a `-port=NNNN`
 * launch argument (default 7777) — so it is documented in the UI but not
 * treated as an editable/exported field here.
 *
 * Sourced from Jagex's own "Dedicated Servers - A How-To Guide" and the
 * community-maintained RuneScape: Dragonwilds Wiki's "Dedicated Servers"
 * page, cross-checked against a third-party host's published config
 * reference for the literal file syntax (section header + key names).
 *
 * This parser is deliberately forgiving: any key=value pair it doesn't
 * recognize is preserved verbatim (not dropped) so a future patch adding
 * new settings, or a hand-edited file with extra keys, round-trips
 * losslessly through this tool.
 */

(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.DragonwildsConfig = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const SECTION_HEADER = '[/Script/Dominion.DedicatedServerSettings]';

  const KNOWN_KEYS = {
    ownerid: 'ownerId',
    servername: 'serverName',
    defaultworldname: 'defaultWorldName',
    adminpassword: 'adminPassword',
    worldpassword: 'worldPassword',
    serverguid: 'serverGuid',
  };

  const FIELD_LABELS = {
    ownerId: 'OwnerId',
    serverName: 'ServerName',
    defaultWorldName: 'DefaultWorldName',
    adminPassword: 'AdminPassword',
    worldPassword: 'WorldPassword',
    serverGuid: 'ServerGuid',
  };

  const MANDATORY_FIELDS = ['ownerId', 'serverName', 'defaultWorldName', 'adminPassword'];

  function emptyValues() {
    return { ownerId: '', serverName: '', defaultWorldName: '', adminPassword: '', worldPassword: '', serverGuid: '' };
  }

  function parseIniText(text) {
    const lines = text.split(/\r\n|\r|\n/);
    const values = emptyValues();
    const otherLines = [];
    const warnings = [];
    let sectionHeader = null;
    let sawAnyKeyValue = false;

    for (const rawLine of lines) {
      const line = rawLine.trim();
      if (line === '' || line.startsWith(';') || line.startsWith('#')) continue;
      if (line.startsWith('[') && line.endsWith(']')) {
        sectionHeader = line;
        continue;
      }
      const eq = line.indexOf('=');
      if (eq === -1) {
        warnings.push(`Ignored a line that isn't in "key=value" format: "${line}"`);
        continue;
      }
      const key = line.slice(0, eq).trim();
      const value = line.slice(eq + 1).trim();
      const field = KNOWN_KEYS[key.toLowerCase()];
      sawAnyKeyValue = true;
      if (field) {
        values[field] = value;
      } else {
        otherLines.push({ key, value });
      }
    }

    if (sectionHeader === null) {
      warnings.push(`No section header line was found (expected "${SECTION_HEADER}"). Any key=value pairs present were still read.`);
    } else if (sectionHeader !== SECTION_HEADER) {
      warnings.push(`Section header is "${sectionHeader}", not the expected "${SECTION_HEADER}". Continuing anyway.`);
    }
    if (!sawAnyKeyValue) {
      warnings.push('No recognizable settings were found in this file. Check that you uploaded the right DedicatedServer.ini.');
    }

    return { values, otherLines, warnings, sectionHeader };
  }

  function missingMandatoryFields(values) {
    return MANDATORY_FIELDS.filter((f) => !values[f]);
  }

  function serializeConfig(values, otherLines) {
    const lines = [SECTION_HEADER];
    lines.push(`OwnerId=${values.ownerId || ''}`);
    lines.push(`ServerName=${values.serverName || ''}`);
    lines.push(`DefaultWorldName=${values.defaultWorldName || ''}`);
    lines.push(`AdminPassword=${values.adminPassword || ''}`);
    lines.push(`WorldPassword=${values.worldPassword || ''}`);
    if (values.serverGuid) lines.push(`ServerGuid=${values.serverGuid}`);
    for (const { key, value } of otherLines || []) {
      lines.push(`${key}=${value}`);
    }
    return lines.join('\r\n') + '\r\n';
  }

  return {
    SECTION_HEADER,
    KNOWN_KEYS,
    FIELD_LABELS,
    MANDATORY_FIELDS,
    emptyValues,
    parseIniText,
    missingMandatoryFields,
    serializeConfig,
  };
});
